### ISSUE TITLE
How to use tuned models

### ISSUE THREAD

**Issue by andersonjoseph** [google/generative-ai-go#103]
Hey!

I'm trying to use tuned models with the SDK, however when using API keys:

```go
client, err := genai.NewClient(ctx, option.WithAPIKey(os.Getenv("API_KEY"))
```

I get the following error: `googleapi: Error 401: API keys are not supported by this API`

I tried to follow [documentation](https://ai.google.dev/gemini-api/docs/oauth) to setup my OAuth credentials. But when I try to create the client like:

```go
data, err := s.ReadFile("./credentials.json")

//...

client, err := genai.NewClient(ctx, option.WithCredentialsJSON(data))
```

I get an error: `You need an API key to use this client`. If I try to set up the API key **and** the credentials I get: `multiple credential options provided`

I'm kind of Lost here, what'd I miss? If someone could point me in the right direction would be great, thanks in advance!

**Comment by eliben** [comment]
You provide a partial sample - can you provide a complete, [minimal reproducer](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for getting the "API keys not supported" message?

**Comment by andersonjoseph** [comment]
I changed my auth flow and could not replicate the `API keys not supported` message. Probably was something on my end with the way I was generating my credentials, however using other auth options still resulted in the `You need an API key to use this client`. error

I opened a [PR ](https://github.com/google/generative-ai-go/pull/105) addressing this issue :)
