### ISSUE TITLE
Problems running protoveneer

### ISSUE THREAD

**Issue by eliben** [google/generative-ai-go#106]
### Description of the bug:

The instructions in `genai/client.go` for running `protoveneer` are difficult to repdoruce.

First, installing protoveneer as instructed fails:

```
$ go install cloud.google.com/go/internal/protoveneer/cmd/protoveneer@latest
go: cloud.google.com/go/internal/protoveneer/cmd/protoveneer@latest: module cloud.google.com/go@latest found (v0.113.0), but does not contain package cloud.google.com/go/internal/protoveneer/cmd/protoveneer
```

Also, the path `../../../googleapis/google-cloud-go/ai/generativelanguage/apiv1beta/generativelanguagepb` assumes a specific local directory structure. It should be encoded in a way that's easier to reproduce on different machines.

(other issues resolved)

**Comment by jba** [comment]
I think I need to tag it. But there is a lot of ceremony to doing that, so instead I'll change the install instructions.

The path to the proto package is a problem. I will change the doc to use an environment variable.

**Comment by eliben** [comment]
> I think I need to tag it. But there is a lot of ceremony to doing that, so instead I'll change the install instructions.

FWIW, this is fine. I don't think we should tag it - it's an internal tool, after all. Cloning the repo and building it isn't a big deal and the new instructions you've added should be easy to follow and work for others.
