### ISSUE TITLE
Support for context caching

### ISSUE THREAD

**Issue by aguynamedben** [google/generative-ai-go#140]
### Description of the feature request:

I'm excited to use the new Gemini [context caching feature](https://ai.google.dev/gemini-api/docs/caching?lang=python) from Golang. Is this planned to be added to this SDK? It look like it was added to the [Python](https://github.com/google-gemini/generative-ai-python/releases/tag/v0.7.0) and [JS](https://github.com/google-gemini/generative-ai-js/releases/tag/%40google%2Fgenerative-ai%400.13.0) SDKs only a few days ago, so I'm curious if/when it will be added to this project.

Also, I'm curious why this project is in the `google` organization and the others are in the `google-gemini` organization? Is this a quasi-supported SDK? Either way, thanks for making it public ❤️

### What problem are you trying to solve with this feature?

I want to use Golang to read in parallel a batch of 100-200 files, upload them to the Gemini Context Cache, then use generative AI on top of them.

**Comment by eliben** [comment]
We're planning to add it, stay tuned

**Comment by eliben** [comment]
Please follow #147

**Comment by jba** [comment]
And #149.

**Comment by eliben** [comment]
This should be available in the newly released v0.15.0

**Comment by aguynamedben** [comment]
epic, nice work... will give it a go!
