### ISSUE TITLE
Can't pass genai.Content to model.GenerateContentStream

### ISSUE THREAD

**Issue by nullcache** [google/generative-ai-go#16]
I want to implement a api which need user pass all chat history every chat, but I can't pass genai.Content to model.GenerateContentStream. It just accept like genai.Text, which doesn't contain role information

**Comment by jba** [comment]
If you look at the [chat implementation](https://github.com/google/generative-ai-go/blob/main/genai/chat.go), you'll see it's already doing that, and it takes care of the roles for you. Do you need something different?

**Comment by nullcache** [comment]
When I check `generative-ai-js`, I find GenerateContentStream can pass Part or Content, which make it more flexible.

I mean, I can see the session implementation. I just want write an api with different input/output request params, I think every query should be stateless, and the history keep in the frontend. User pass all historys in every query. So I think the sdk should allow users to manage history by themselves or just can pass all historys to GenerateContentStream.

The only way I find to implement my needs I think is StartChat in every request (every request to me), and append old historys to ChatSession.History slice, then SendMessageStream. Does it meet expectations ?

**Comment by SnailWhb** [comment]
func (cs *ChatSession) SendMessageStreamFromHistroys(ctx context.Context, contents []*Content) *GenerateContentResponseIterator {
	req := cs.m.newGenerateContentRequest(contents...)
	req.GenerationConfig.CandidateCount = Ptr[int32](1)
	streamClient, err := cs.m.c.c.StreamGenerateContent(ctx, req)
	return &GenerateContentResponseIterator{
		sc:  streamClient,
		err: err,
		cs:  cs,
	}
}

**Comment by nullcache** [comment]
> model := g.Client.GenerativeModel(model_name) model.SetTemperature(0.9) model.SetTopP(0.2) model.SetTopK(1) model.SetMaxOutputTokens(4000) model.SetCandidateCount(1) chatSession := model.StartChat() history := g.ChatCompletionMessageToGeminiHistory(messages[:len(messages)-1]) chatSession.History = history
> 
> stream := chatSession.SendMessageStream(ctx, genai.Text(messages[0].Content))

So as I have metioned, is it the only to resolve? 
And I think maybe it's better to provide a tool function in this library.
I just notice that js implementation is more flexible, so I mean maybe `toContent` interface is better than `toPart`?

**Comment by eliben** [comment]
@nullcache it's not clear what you're asking for beyond what `ChatSession` (see example: https://pkg.go.dev/github.com/google/generative-ai-go/genai#example-ChatSession) already provides.

Can you please clarify?

Note that `GenerateContent` is designed for one-shot interactions, and you can still provide context by including it in the prompt. If you need a chat-like interaction with roles, that's what `ChatSession` is for; is there something you need that it doesn't provide?
