### ISSUE TITLE
type Tool example fails

### ISSUE THREAD

**Issue by mskyan** [google/generative-ai-go#160]
### Description of the bug:

https://pkg.go.dev/github.com/google/generative-ai-go@v0.16.0/genai#example-Tool

OS: Windows 10
Go: 1.22.4

at this line: 
	res, err := session.SendMessage(ctx, genai.Text("What is the weather like in New York?"))
	if err != nil {
		log.Fatal(err)
	}

returns "googleapi: Error 400: exit status 1"

### Actual vs expected behavior:

no error

### Any other information you'd like to share?

Confirmed same GOOGLE_API_KEY working on a Python code.
https://colab.research.google.com/github/google/generative-ai-docs/blob/main/site/en/gemini-api/docs/function-calling/python.ipynb

**Comment by eliben** [comment]
I confirm I can see this too - investigating
