### ISSUE TITLE
SetTemperature() followed by Info()

### ISSUE THREAD

**Issue by jdevoo** [google/generative-ai-go#169]
### Description of the bug:

I set an arbitrary temperature using SetTemperature then query model information with Info but I only see "1.0" returned. Is Info() only returning default model values?

### Actual vs expected behavior:

`model.SetTemperature(float32(*tempVal))`
followed by
`info, err := model.Info(ctx)` where info.Tempterature always returns 1

**Comment by eliben** [comment]
@jdevoo correct, it's the default, see documentation:

```
// This value specifies default to be used by the backend while making the
// call to the model.
```

**Comment by jdevoo** [comment]
Missed that! Ok. I was looking to make my tool show the actual values used by the mode in generation, after overriding model values.
