### ISSUE TITLE
Improve `MIMEType` documentation in the context of uploading and uses file

### ISSUE THREAD

**Issue by fredsa** [google/generative-ai-go#180]
### Description of the bug:

There three ways to set an file's MIME type:
1. Relying on an automatic (server-side? client-side?) determination
1. When uploading a file, via [`UploadFileOptions`](https://pkg.go.dev/github.com/google/generative-ai-go/genai#UploadFileOptions) > `MIMEType`
1. When generating content using a previously uploaded file, via [`genai.FileData`](https://pkg.go.dev/github.com/google/generative-ai-go/genai#FileData) > `MIMEType`

With some testing, it appears that
- Automatic determination isn't always great (yet?); while it handles files with unique identification headers such images and PDFs, it's less stellar with more nuanced assessments, for example determining whether a text file is plain text (`text/plain`) or Markdown (`text/markdown`)
- Specifying a MIME Type on upload effectively sets the file's metadata
- Specifying a MIME Type during usage effectively overrides the file's metadata

Suggested changes:
1. https://pkg.go.dev/github.com/google/generative-ai-go/genai#UploadFileOptions >
   `MIMEType string // the MIME type of the file; if omitted, it will be inferred` to:
   - Note that the MIME type will be stored as metadata
   - Specify how/where the the MIME type is inferred, i.e. "on/by the server", "by <name of Go pkg/API>"
   - Mention `IANA`, like below
    - Link to [supported MIME types](https://ai.google.dev/gemini-api/docs/prompting_with_media?lang=go#supported_file_formats)
1. https://pkg.go.dev/github.com/google/generative-ai-go/genai#FileData >
    `MIMEType string // Optional. The IANA standard MIME type of the source data.` to:
    - Note that this MIME type is a optional override to the file metadata that was specified (or determined) during upload
    - Link to [supported MIME types](https://ai.google.dev/gemini-api/docs/prompting_with_media?lang=go#supported_file_formats)
1. https://pkg.go.dev/github.com/google/generative-ai-go/genai#Client.UploadFile > Example should:
    - Should (as a best practice) specify a MIME type via `UploadFileOptions`; an clarifying comment to indicate how/where
       the MIME type will be determined if none is specified could be useful
    - Would be helpful to note the specifying MIME type is a best practice, especially if the the correct MIME type cannot be
       determined reliably, such as with certain `text/*` MIME types
    -  If the above suggested fix to improve the documentation for `FileData > `MIMEType` isn't followed, strongly consider
        a comment above the `model.GenerateContent(ctx, genai.FileData{URI: file.URI})` line about the potential to
        to override the MIME type, ideally with a reason why one would need or want to do so in a real-world application.
       Note, that otherwise a lack of a comment can lead to developers discovering (e.g. through IDE tooling) the `MIMEType`
       field here, and wondering about its usage.
1. https://pkg.go.dev/github.com/google/generative-ai-go/genai#Client.UploadFile > name (`The name may be empty, in which case a unique name will be generated. Otherwise, it can contain up to 40 characters that are lowercase alphanumeric or dashes (-), not starting or ending with a dash. The string "files/" is prepended to the name if it does not contain a '/'.`) should:
    - Be reworded to communicate that this field is (or can be thought of) effectively a 40 character ID (that's treated like a
       filename); because we're dealing with file uploads, and we're dealing with a `name` argument, there's a strong
       suggestion that this is a filename; to fight his misleading assumption, rewording the description to make it clear that
       this is a (short-ish) unique identifier is helpful
    - Consider recommending or suggesting that most uses cases should use an autogenerated
    - For the use case in which the developer needs/wants to use an id (`name`) of their choosing, suggest a way to generate
       a name, such as SHA-1.
    - Note that (currently) "files/" is the only supported prefix.

**Comment by eliben** [comment]
cc @jba - we were talking about MIME issues with automatic detection; documentation is another important side of it (but we should see what we can fix in the SDK code first)

**Comment by jba** [comment]
Thanks, Fred, for those wonderfully detailed comments.
#183 does everything except the example. I will leave that to Eli.

**Comment by eliben** [comment]
Re the example, in `main` we've factored out a function to upload a file for many examples, and it shows up on the doc page. It already tweaks MIMEtype for text files, and I just sent a PR that adds a comment to that to be clearer.

Once this set of new samples lands, I will tag a new release so pkgsite will show the latest documentation (there are tons of new examples now, as part of the cross-SDK samples work)

**Comment by fredsa** [comment]
Thanks, left a comment on that PR: https://github.com/google/generative-ai-go/pull/184/files#r1683356880

**Comment by eliben** [comment]
@fredsa please let us know if anything else needs to be done to address this

**Comment by fredsa** [comment]
Updates looks great. Feel free to close.


For (future) consideration:
https://github.com/google/generative-ai-go/pull/185#discussion_r1684905898
