### ISSUE TITLE
Add a more descriptive error for text/plain files that are not UTF-8

### ISSUE THREAD

**Issue by handsomefox** [google/generative-ai-go#221]
### Description of the bug:

I've had to recently debug an issue .txt file. We had no conversions to UTF-8 inplace and this resulted in a confusing problem, where Gemini uploads just result in:

```
googleapi: got HTTP response code 400 with body: [{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Request contains an invalid argument.\",\n    \"status\": \"INVALID_ARGUMENT\"\n  }\n}\n]"
```

This pretty much gives you nothing and I've spent some time to debug.

I think two things can fix this issue for future users:
1. The docs for `client.UploadFile` can better indicate that UTF-8 is required for text files, or validate it itself.
2. The API error that we get should include more details about happened.

The validation in the first point is quite easy if you decode the content-type correctly, since anything that begins with text/ you can just call `utf8.Valid(b)` on.
The second point I have no idea about.

You could also provide a conversion method for generic cases like `UTF16(LE/BE)` and `Windows 1252/1251` since they're quite common.

**Comment by eliben** [comment]
We're trying not to add validation around the backend model, but we could perhaps document this better

@jba WDYT?

**Comment by jba** [comment]
We should document that UTF-8 is required, and add tests to make sure that it is indeed broken for non-UTF-8. That way if the backend learns non-UTF-8, we will know to remove the doc.

**Comment by eliben** [comment]
@handsomefox can you link an example of a text file encoded in 1252 or whatever you tried, that gave you this error?
I sent #224 with a test for a generic bad encoding, which seems to result in a different error from the service

**Comment by handsomefox** [comment]
@eliben i've retested all of these files and they've all returned `[{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Request contains an invalid argument.\",\n    \"status\": \"INVALID_ARGUMENT\"\n  }\n}\n]`

[utf16le.txt](https://github.com/user-attachments/files/17873002/utf16le.txt)
[1251.txt](https://github.com/user-attachments/files/17873005/1251.txt)
[1252.txt](https://github.com/user-attachments/files/17873006/1252.txt)

From the differences from your test, I can only see that I'm using ChatSession.SendMessage instead of Model.GenerateContent.

**Comment by eliben** [comment]
I've sent #228 adding one of the files @handsomefox uploaded, it indeed errors out as described.

W.r.t. updating the documentation - the natural place for this seems to be https://pkg.go.dev/github.com/google/generative-ai-go/genai#UploadFileOptions, but it already documents the MIME pointing to a link that was redirected and now doesn't seem to contain the required information. I think we should find where the supported MIME types are described now.
