### ISSUE TITLE
support frequencyPenalty

### ISSUE THREAD

**Issue by dongsuo** [google/generative-ai-go#222]
### Description of the feature request:

https://ai.google.dev/api/generate-content#v1beta.GenerationConfig
Looks the sdk doesn't support frequencyPenalty config now

**Comment by gmKeshari** [comment]
Hi @dongsuo,

Which Gemini model you are using?? The new 002 models support "frequencyPenalty". Please refer this [cookbook](https://github.com/google-gemini/cookbook/blob/main/quickstarts/New_in_002.ipynb).

**Comment by jba** [comment]
The [unified SDK](https://pkg.go.dev/google.golang.org/genai) supports it.
