### ISSUE TITLE
ExampleTool in Examples file panics

### ISSUE THREAD

**Issue by ajroetker** [google/generative-ai-go#225]
### Description of the bug:

https://github.com/google/generative-ai-go/blob/main/genai/example_test.go#L1185-L1191
There's a panic because of an unchecked error and a nil resp, the actual SendMessage of the FunctionResponse is 400'ing
Is the example just broken or are function responses not yet supported?

**Comment by jba** [comment]
https://github.com/google/generative-ai-go/pull/226 should fix this.

**Comment by ajroetker** [comment]
Awesome @jba thanks for the quick turnaround!

**Comment by sunshineplan** [comment]
@jba Thanks for the fix! When can we expect a new release with these changes?

**Comment by eliben** [comment]
> [@jba](https://github.com/jba) Thanks for the fix! When can we expect a new release with these changes?

Release v0.19.0 is now out, please update
