### ISSUE TITLE
func (iter *GenerateContentResponseIterator) Next() (*GenerateContentResponse, error) doesn't return the full error

### ISSUE THREAD

**Issue by yfzhou0904** [google/generative-ai-go#24]
I'm using Gemini Pro model to generate chat messages. When iter.Next() returns an error, only part of the error string is included, e.g. "googleapi: Error 400:". How can I see the full message?

**Comment by jba** [comment]
The error comes from a lower-level client. Here is some [general information on inspecting the errors](https://pkg.go.dev/cloud.google.com/go#hdr-Inspecting_errors).
In this particular case, I found that this code worked well:
```
import "google.golang.org/api/googleapi"
...
    var gerr *googleapi.Error
   if errors.As(err, &gerr) {
        fmt.Println(gerr)
   }
```

**Comment by yfzhou0904** [comment]
> The error comes from a lower-level client. Here is some [general information on inspecting the errors](https://pkg.go.dev/cloud.google.com/go#hdr-Inspecting_errors). In this particular case, I found that this code worked well:
> 
> ```
> import "google.golang.org/api/googleapi"
> ...
>     var gerr *googleapi.Error
>    if errors.As(err, &gerr) {
>         fmt.Println(gerr)
>    }
> ```

Thanks!
