### ISSUE TITLE
Can PDF data be passed as a Blob

### ISSUE THREAD

**Issue by sdeoras** [google/generative-ai-go#27]
This is not a bug. I am just wondering if PDF buffer can be passed?

```
part := genai.Blob{
		MIMEType: "application/pdf",
		Data:     pdfBytes,
	}
```
When trying to do so, I get following error:
```
googleapi: Error 400: Request contains an invalid argument.
```

Thanks for your help

**Comment by jba** [comment]
No, the "gemini-pro" model accepts only text, and the "gemini-pro-vision" model accepts only text and images.
