### ISSUE TITLE
Some errors could be more descriptive

### ISSUE THREAD

**Issue by sdeoras** [google/generative-ai-go#28]
Some errors are without any description, such as
```
googleapi: Error 400:
```

This happens if only text is being sent to `gemini-pro-vision` model without any image data.

This could be improved. Thanks.

**Comment by sdeoras** [comment]
What is the best way to have a `chat` with the model related to images that were previously sent to the model?

**Comment by jba** [comment]
For help with the errors, see https://github.com/google/generative-ai-go/issues/24#issuecomment-1860617429.

> What is the best way to have a chat with the model related to images that were previously sent to the model?

You have to send the images as part of the chat session. The models are stateless and have no memory of previous interactions.

**Comment by sdeoras** [comment]
> For help with the errors, see [#24 (comment)](https://github.com/google/generative-ai-go/issues/24#issuecomment-1860617429).
> 
> > What is the best way to have a chat with the model related to images that were previously sent to the model?
> 
> You have to send the images as part of the chat session. The models are stateless and have no memory of previous interactions.

Are all models stateless? Somehow `gemini-pro` model seems to remember history in the chat session. For instance, if I ask it to generate 10 random numbers and subsequently ask to calculate the average value in next prompt, it seems to be doing the right thing.

Anyway, for now I'll assume that chat is only compatible with `gemini-pro` and image analysis can only work with `gemini-pro-vision` and it will be stateless.

**Comment by jba** [comment]
It isn't the model that's remembering history, it's the chat session itself.
The chat session sends the entire history to the model—that is, to the remote service that is doing the work—every time you call SendMessage.

Why can't you use a chat session with gemini-pro-vision?

**Comment by sdeoras** [comment]
> It isn't the model that's remembering history, it's the chat session itself. The chat session sends the entire history to the model—that is, to the remote service that is doing the work—every time you call SendMessage.
> 
> Why can't you use a chat session with gemini-pro-vision?

Thanks, got it. My understanding of how history was maintained was incorrect.
