### ISSUE TITLE
Any way to add System Prompt like OpenAI

### ISSUE THREAD

**Issue by vsumit89** [google/generative-ai-go#31]
We(current org) are building an aggregation platform which has number of genAI models and want to to in a way standardise our chat model and system prompt is an important part of it, so just wanted to check is there any way I can add something like a system prompt

**Comment by 496672097** [comment]
yes,i need't too。But the role just "user"、"model"。

**Comment by eliben** [comment]
Right now the best way to do it is to just prepend what you consider a "system prompt" to the rest.

Gemini prompts are multi-part, so you can make `part[0]` be your "system" prompt.

**Comment by jba** [comment]
As of #84, this is available as `Model.SystemInstruction`.
