### ISSUE TITLE
[Bug] Authentication Error with CountTokens in generative-ai-go Client Library

### ISSUE THREAD

**Issue by H0llyW00dzZ** [google/generative-ai-go#33]
### Description
When using the [`CountTokens`](https://github.com/google/generative-ai-go/blob/v0.5.0/genai/client.go#L200) function from the [`generative-ai-go`](https://pkg.go.dev/github.com/google/generative-ai-go/genai) client library, I am experiencing an authentication error. This occurs even though my API key is valid and works as expected for other interactions with the AI, such as sending and receiving chat messages.

### Error Message
The error message I receive is as follows:
```
oauth2: "invalid_grant" "reauth related error (invalid_rapt)"
```

### Steps to Reproduce
1. Initialize a new generative AI client using a valid API key.
2. Call the `CountTokens` function with a sample input string.
3. Observe the authentication error.

### Expected Behavior
The `CountTokens` function should return the number of tokens in the input string without any authentication issues, similar to other functions in the library that interact with the AI.

### Actual Behavior
The function returns an authentication error, indicating an issue with the token grant or reauthentication process.

### Code Snippet
Here is the code snippet I am using to count tokens:

```go
func CountTokens(apiKey, input string) (int, error) {
	ctx := context.Background()
	client, err := genai.NewClient(ctx, option.WithAPIKey(apiKey))
	if err != nil {
		return 0, err
	}
	defer client.Close()

	model := client.GenerativeModel(ModelAi)

	resp, err := model.CountTokens(ctx, genai.Text(input))
	if err != nil {
		return 0, err
	}

	return int(resp.TotalTokens), nil
}
```

### Screenshots
- Documentation reference for [`CountTokens`](https://pkg.go.dev/github.com/google/generative-ai-go/genai#GenerativeModel.CountTokens) function:

![image](https://github.com/google/generative-ai-go/assets/17626300/db3c27b2-075b-487d-91d1-67c132b3ee41)

- Error message received:

![image](https://github.com/google/generative-ai-go/assets/17626300/18405f12-0eb7-43b5-927f-aadc7ee12193)

**Comment by H0llyW00dzZ** [comment]
another screenshot:

Authentication Error with CountTokens in generative-ai-go Client Library

![image](https://github.com/google/generative-ai-go/assets/17626300/356ec33f-cfd2-4f5f-9ca0-dc298127b371)

**Comment by aucub** [comment]
I've tested your code and discovered that it should function correctly if the apiKey is appropriately set. I noticed that you've defined the apiKey in the main package and assigned its value when creating the genai.Client via NewSession(). However, you've also defined the apiKey in the terminal package without assigning it any value, and then this uninitialized apiKey was subsequently used in session.go
![截图 2024-01-13 19-28-56](https://github.com/google/generative-ai-go/assets/78630225/3e709395-2dd6-46e2-abb4-ea74af556b3c)

**Comment by H0llyW00dzZ** [comment]
> I've tested your code and discovered that it should function correctly if the apiKey is appropriately set. I noticed that you've defined the apiKey in the main package and assigned its value when creating the genai.Client via NewSession(). However, you've also defined the apiKey in the terminal package without assigning it any value, and then this uninitialized apiKey was subsequently used in session.go ![截图 2024-01-13 19-28-56](https://private-user-images.githubusercontent.com/78630225/296449013-3e709395-2dd6-46e2-abb4-ea74af556b3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTg0MjEsIm5iZiI6MTcwNTQxODEyMSwicGF0aCI6Ii83ODYzMDIyNS8yOTY0NDkwMTMtM2U3MDkzOTUtMmRkNi00NmUyLWFiYjQtZWE3NGFmNTU2YjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE1MTUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMzNjNjA0MzRmZDZhNTkyM2ZhNmFjNzdiM2IwOGMzYTMwYzA4M2EyNmRkYzRlOGIyODRiODY0OGYxZmM4YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7_misnwMyaiV-eHf0OuWMn8pvz-DsyBRBl1dSEDqeIo)

yeah it fixed now,
https://github.com/H0llyW00dzZ/GoGenAI-Terminal-Chat/pull/113
I forgot the count token are not part of gemini-pro session
