### ISSUE TITLE
connect error

### ISSUE THREAD

**Issue by ericosmic** [google/generative-ai-go#37]
I try to use python api to utility gemini model , but it give connection error like below:
<img width="2144" alt="image" src="https://github.com/google/generative-ai-go/assets/35327931/3c26094c-a9e7-45f1-b3cf-ef7343c7811e">

the complete error info:
`Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised RetryError: Deadline of 60.0s exceeded while calling target function, last exception: 503 failed to connect to all addresses; last error: UNAVAILABLE: ipv4:142.251.43.10:443: Failed to connect to remote host: FD shutdown.
`

ps: I using a proxy to send request.

**Comment by jba** [comment]
This is the repo for Go. Try https://github.com/google/generative-ai-python.
