### ISSUE TITLE
Nil Pointer Exception in CitationSources slice

### ISSUE THREAD

**Issue by ducknificient** [google/generative-ai-go#60]
Dear maintainer, 

after digging deeper to the library, i found out that all of the source is generated by protoc-gen-go and has the label do not edit.

While I don't have access to the real source code from citation.pb.go , i saw that there's a potential nil pointer error based on the generated code. For example in `apiv1/generativelanguagepb/citation.pb.go ` line 81-86

```
func (x *CitationMetadata) GetCitationSources() []*CitationSource {
	if x != nil {
		return x.CitationSources
	}
	return nil
}
```
instead of returning nil, the slice need to be initialized first to avoid nil pointer exception of the CitationMetadata struct.

```
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: google/ai/generativelanguage/v1/citation.proto
```

I'm still learning about pointers, and led to a question. Does the nil handling implemented at clientside (as user), at the library level, at the protoc-gen-go, at the compiler (go programming it self), or at go-pls (adding warning ?

continuing from PR #59 

Best Regards,

**Comment by jba** [comment]
Good question. In Go, we don't fill the code with nil pointer checks. It's up to the ultimate user to make those checks.

For example, in the code you quoted, there is no nil pointer error. It is impossible for that code to panic. It may return a nil slice, but it is common for functions to do so. For example, here is a perfectly valid Go function that returns a nil slice if given a slice of all odd numbers:
```
func evens(nums []int) []int {
    var res []int
    for _, n := range nums {
        if n % 2 == 0 {
            res = append(res, n)
        }
    }
    return res
}
```
The right way to use this function, for example to access the first element, is to check using `len`:
```
evs := evens(myNumberSlice)
if len(evs) > 0 {
   fmt.Println("first even number:", evs[0])
}
```
