### ISSUE TITLE
How to pass location to the client?

### ISSUE THREAD

**Issue by laszukdawid** [google/generative-ai-go#74]
**Disclaimer**: I'm only dabbling with golang so likely there's something obvious missing. Apologies for this. However, I was not able to find much information through traditional search, nor using most LLMs.

### Question
How can I specify a location when instantiating the Client? The [vertexai/genai](https://pkg.go.dev/cloud.google.com/go/vertexai/genai) seems to allow the `location` as one of the parameters. I'm guessing that with your client, it needs to come through one of the Options, maybe the Endpoint? If so, what's the endpoint? I tried `https://{region}-aiplatform.googleapis.com` per [Vertex AI doc](https://cloud.google.com/vertex-ai/docs/general/locations#choosing_your_location), though, now that I'm thinking about it, I'm not sure if that's the same service (is it?).

As you might tell, I have very little experience with GCP. If there's a canonical way on setting the location on the client/session then I'm keen learning.

**Comment by eliben** [comment]
This repository is for the non-GCP service at ai.google.dev

The steps in https://github.com/google/generative-ai-go?tab=readme-ov-file#try-out-the-api is all you need to get started, you do not need a GCP project or location.

**Comment by laszukdawid** [comment]
Thanks for the reference. Unfortunately what's written in the readme, neither examples in docs, nor actually following documentation didn't help. I'm getting that there is no selected model in given location (only using the Key).

All the best.

**Comment by eliben** [comment]
I'm not sure I understand the issue you're describing. Can you provide a minimal, reproducible example (per https://stackoverflow.com/help/minimal-reproducible-example) of what's wrong? You may want to create a separate issue for that since I think this issue's original question has been answered

**Comment by laszukdawid** [comment]
I see. Ok, that's even more confusing. For one, I'm in Canada, and it seems that Google doesn't recognize such country. Also, had to re-read your comment that this is a separate service from GCP, though with most code, documentation, names either similar sounding or exactly the same. Thank you for the explanation, I see where I've made a mistake.
