### ISSUE TITLE
Unsupported MIME type when running the example with a very simple text file

### ISSUE THREAD

**Issue by arkadyb** [google/generative-ai-go#90]
Hi, every time i aim to upload and generate on a very simple random text file i get:

`
"Unsupported MIME type: text/plain; charset=utf-8"
`

The code is equal to https://pkg.go.dev/github.com/google/generative-ai-go/genai#Client.UploadFile, except for the model version. The one i have access to is `gemini-1.0-pro`.

Is it the model issue? 

Thanks,

**Comment by arkadyb** [comment]
Hey @jba , sorry, was the wrong link. I update the link in the original post. The code literally exactly as that one from the example, except for the model name.

**Comment by jba** [comment]
Use gemini-1.5-pro-latest.

**Comment by arkadyb** [comment]
That model is not yet  in GA. It would be good to outline in the documentation the latest model is a hard requirement.
